version: "3.3"
services:
  mishipayapp:
    container_name: mishipayapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      NODE_ENV: production
